# Generated by Django 4.2.5 on 2023-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, upload_to='musics'),
        ),
    ]
