# Generated by Django 4.2.6 on 2023-10-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_playlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.playlist'),
        ),
    ]
